name: pull-request

on: pull_request

jobs:
  pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Configure node
        uses: actions/setup-node@master
        with:
          node-version: "12.x"

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn just lint

      - name: Test
        run: yarn just test

      - name: Test docs
        run: yarn just test-docs

      - name: Build
        run: yarn just build
